builds:
  - binary: eck-diagnostics-parser
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./cmd/

release:
  prerelease: auto

universal_binaries:
  - replace: true


checksum:
  name_template: 'checksums.txt'